#!/usr/bin/env python3
"""Convert SPP event log into one-row-per-candidate training table.

No external Python packages are required.

Input: CSV produced by 04_patch_spp_candidate_logger.sh, with event rows:
  CAND,...  candidate generated by SPP
  USE,...   later demand access marked useful_prefetch by ChampSim

Output: CSV schema expected by rl_filter_story_starter.ipynb:
  trace,cycle,ip,addr,pf_addr,delta,spp_confidence,cache_hit,
  mshr_occupancy,mshr_size,pq_occupancy,pq_size,
  recent_spp_accuracy,recent_pc_accuracy,recent_delta_accuracy,
  bandwidth_bucket,set_pressure,
  outcome_useful,outcome_late,outcome_evicted_unused,outcome_duplicate

Important limitations of this first converter:
- cycle is event order, because the current event logger does not yet record CPU cycle.
- outcome_late and outcome_evicted_unused are set to 0 for now.
- PQ occupancy is whatever the logger wrote; current logger writes 0 because internal_PQ is private.
- outcome_useful is assigned by matching candidate pf_addr to later USE addr.
"""

import argparse
import csv
from collections import defaultdict, deque
from pathlib import Path

OUT_COLUMNS = [
    "trace",
    "cycle",
    "ip",
    "addr",
    "pf_addr",
    "delta",
    "spp_confidence",
    "cache_hit",
    "mshr_occupancy",
    "mshr_size",
    "pq_occupancy",
    "pq_size",
    "recent_spp_accuracy",
    "recent_pc_accuracy",
    "recent_delta_accuracy",
    "bandwidth_bucket",
    "set_pressure",
    "outcome_useful",
    "outcome_late",
    "outcome_evicted_unused",
    "outcome_duplicate",
]

INT_FIELDS = [
    "cand_id",
    "addr",
    "ip",
    "pf_addr",
    "delta",
    "confidence",
    "fill_l2",
    "cache_hit",
    "mshr_occupancy",
    "mshr_size",
    "pq_occupancy",
    "pq_size",
    "useful_prefetch",
    "depth",
]


def safe_int(x, default=0):
    try:
        if x is None or x == "":
            return default
        return int(float(x))
    except Exception:
        return default


def load_events(path):
    events = []
    with path.open(newline="") as f:
        reader = csv.DictReader(f)
        for idx, row in enumerate(reader):
            clean = {k: v for k, v in row.items()}
            clean["event_idx"] = idx
            for field in INT_FIELDS:
                clean[field] = safe_int(clean.get(field, 0))
            events.append(clean)
    return events


def assign_useful_labels(events):
    """Match each USE address to the oldest earlier unmatched CAND with same pf_addr."""
    cands = []
    global_to_local = {}

    for row in events:
        if row.get("event") == "CAND":
            c = dict(row)
            c["outcome_useful"] = 0
            c["use_event_idx"] = -1
            global_to_local[c["event_idx"]] = len(cands)
            cands.append(c)

    seen_waiting = defaultdict(deque)

    for row in events:
        ev = row.get("event")
        if ev == "CAND":
            local_i = global_to_local.get(row["event_idx"])
            if local_i is not None:
                seen_waiting[row["pf_addr"]].append(local_i)
        elif ev == "USE":
            addr = row["addr"]
            if seen_waiting[addr]:
                local_i = seen_waiting[addr].popleft()
                if cands[local_i]["outcome_useful"] == 0:
                    cands[local_i]["outcome_useful"] = 1
                    cands[local_i]["use_event_idx"] = row["event_idx"]

    return cands


def add_online_recent_accuracy(cands):
    """Add prior-only recent accuracy features in event order."""
    cands.sort(key=lambda r: r["event_idx"])

    global_seen = 0
    global_useful = 0
    pc_seen = defaultdict(int)
    pc_useful = defaultdict(int)
    delta_seen = defaultdict(int)
    delta_useful = defaultdict(int)

    for row in cands:
        ip = row["ip"]
        delta = row["delta"]

        row["recent_spp_accuracy"] = global_useful / float(global_seen) if global_seen else 0.5
        row["recent_pc_accuracy"] = pc_useful[ip] / float(pc_seen[ip]) if pc_seen[ip] else 0.5
        row["recent_delta_accuracy"] = delta_useful[delta] / float(delta_seen[delta]) if delta_seen[delta] else 0.5

        y = int(row["outcome_useful"])
        global_seen += 1
        global_useful += y
        pc_seen[ip] += 1
        pc_useful[ip] += y
        delta_seen[delta] += 1
        delta_useful[delta] += y

    return cands


def build_candidate_table(events, trace):
    cands = assign_useful_labels(events)
    cands = add_online_recent_accuracy(cands)

    seen_pf = set()
    rows = []
    for c in cands:
        pf = c["pf_addr"]
        duplicate = 1 if pf in seen_pf else 0
        seen_pf.add(pf)

        rows.append({
            "trace": trace,
            "cycle": c["event_idx"],
            "ip": c["ip"],
            "addr": c["addr"],
            "pf_addr": c["pf_addr"],
            "delta": c["delta"],
            "spp_confidence": c["confidence"],
            "cache_hit": c["cache_hit"],
            "mshr_occupancy": c["mshr_occupancy"],
            "mshr_size": c["mshr_size"],
            "pq_occupancy": c["pq_occupancy"],
            "pq_size": c["pq_size"],
            "recent_spp_accuracy": "{:.6f}".format(c["recent_spp_accuracy"]),
            "recent_pc_accuracy": "{:.6f}".format(c["recent_pc_accuracy"]),
            "recent_delta_accuracy": "{:.6f}".format(c["recent_delta_accuracy"]),
            "bandwidth_bucket": 0,
            "set_pressure": 0,
            "outcome_useful": int(c["outcome_useful"]),
            "outcome_late": 0,
            "outcome_evicted_unused": 0,
            "outcome_duplicate": duplicate,
        })
    return rows


def write_rows(path, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=OUT_COLUMNS)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--events", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--trace", default="unknown")
    args = ap.parse_args()

    events = load_events(args.events)
    rows = build_candidate_table(events, args.trace)
    write_rows(args.out, rows)

    total = len(rows)
    useful = sum(int(r["outcome_useful"]) for r in rows)
    acc = useful / float(total) if total else 0.0
    mshr_vals = [int(r["mshr_occupancy"]) for r in rows]
    mshr_avg = sum(mshr_vals) / float(total) if total else 0.0
    mshr_max = max(mshr_vals) if mshr_vals else 0

    print("[events]", args.events)
    print("[out]", args.out)
    print("[candidates]", total)
    print("[useful]", useful)
    print("[candidate accuracy]", "{:.6f}".format(acc))
    print("[mshr avg]", "{:.3f}".format(mshr_avg))
    print("[mshr max]", mshr_max)


if __name__ == "__main__":
    main()
