#!/usr/bin/env python3
"""Convert SPP event log into one-row-per-candidate training table.

No external Python packages are required.

Input: CSV produced by 04_patch_spp_candidate_logger.sh, with event rows:
  CAND,...  candidate generated by SPP
  USE,...   later demand access marked useful_prefetch by ChampSim

Output schema:
  trace,cycle,ip,addr,pf_addr,delta,spp_confidence,spp_fill_l2,spp_issued,cache_hit,
  mshr_occupancy,mshr_size,pq_occupancy,pq_size,
  recent_spp_accuracy,recent_pc_accuracy,recent_delta_accuracy,
  bandwidth_bucket,set_pressure,
  outcome_useful,outcome_late,outcome_evicted_unused,outcome_duplicate

Scopes:
  all              all logged SPP candidates
  spp_l2_issue     candidates with fill_l2/confidence>=threshold
  spp_actual_issue candidates for which prefetch_line() accepted/issued the request

The loader also handles one transitional log format where CAND rows already contain
an extra `issued` field but the CSV header was still the old no-issued header. In
that case it shifts fields back into the correct positions automatically.
"""

import argparse
import csv
import gzip
import lzma
from collections import defaultdict, deque
from pathlib import Path

OUT_COLUMNS = [
    "trace",
    "cycle",
    "ip",
    "addr",
    "pf_addr",
    "delta",
    "spp_confidence",
    "spp_fill_l2",
    "spp_issued",
    "cache_hit",
    "mshr_occupancy",
    "mshr_size",
    "pq_occupancy",
    "pq_size",
    "recent_spp_accuracy",
    "recent_pc_accuracy",
    "recent_delta_accuracy",
    "bandwidth_bucket",
    "set_pressure",
    "outcome_useful",
    "outcome_late",
    "outcome_evicted_unused",
    "outcome_duplicate",
]

INT_FIELDS = [
    "cand_id",
    "addr",
    "ip",
    "pf_addr",
    "delta",
    "confidence",
    "fill_l2",
    "issued",
    "cache_hit",
    "mshr_occupancy",
    "mshr_size",
    "pq_occupancy",
    "pq_size",
    "useful_prefetch",
    "depth",
]


def safe_int(x, default=0):
    try:
        if x is None or x == "":
            return default
        return int(float(x))
    except Exception:
        return default


def recover_shifted_issued_row(row):
    """Recover rows with old header but new extra issued field.

    Old header:
      ...,fill_l2,cache_hit,mshr_occupancy,mshr_size,pq_occupancy,pq_size,useful_prefetch,depth

    New row payload:
      ...,fill_l2,issued,cache_hit,mshr_occupancy,mshr_size,pq_occupancy,pq_size,useful_prefetch,depth

    csv.DictReader stores the last extra value under key None. We shift the
    affected columns so downstream code can use `issued` normally.
    """
    extras = row.get(None)
    if not extras:
        return row, False

    fixed = dict(row)
    fixed.pop(None, None)
    fixed["issued"] = row.get("cache_hit", 0)
    fixed["cache_hit"] = row.get("mshr_occupancy", 0)
    fixed["mshr_occupancy"] = row.get("mshr_size", 0)
    fixed["mshr_size"] = row.get("pq_occupancy", 0)
    fixed["pq_occupancy"] = row.get("pq_size", 0)
    fixed["pq_size"] = row.get("useful_prefetch", 0)
    fixed["useful_prefetch"] = row.get("depth", 0)
    fixed["depth"] = extras[0] if extras else 0
    return fixed, True


def load_events(path):
    events = []
    opener = open
    if str(path).endswith(".gz"):
        opener = gzip.open
    elif str(path).endswith(".xz"):
        opener = lzma.open

    with opener(path, "rt", newline="") as f:
        reader = csv.DictReader(f)
        explicit_issued_col = reader.fieldnames is not None and "issued" in reader.fieldnames
        inferred_issued_col = False
        for idx, row in enumerate(reader):
            if explicit_issued_col:
                clean = {k: v for k, v in row.items() if k is not None}
                row_has_issued = True
            else:
                clean, recovered = recover_shifted_issued_row(row)
                row_has_issued = recovered
                inferred_issued_col = inferred_issued_col or recovered

            clean["event_idx"] = idx
            clean["has_issued_col"] = explicit_issued_col or row_has_issued
            for field in INT_FIELDS:
                clean[field] = safe_int(clean.get(field, 0))
            events.append(clean)

    if events:
        has_any_issued = explicit_issued_col or inferred_issued_col
        for e in events:
            e["has_issued_col"] = has_any_issued
    return events


def l2_intent(row, min_confidence):
    return int(row.get("fill_l2", 0)) == 1 or int(row.get("confidence", 0)) >= min_confidence


def is_in_scope(row, scope, min_confidence):
    if row.get("event") != "CAND":
        return False
    if scope == "all":
        return True
    if scope == "spp_l2_issue":
        return l2_intent(row, min_confidence)
    if scope == "spp_actual_issue":
        if row.get("has_issued_col", False):
            return int(row.get("issued", 0)) == 1
        return l2_intent(row, min_confidence)
    raise ValueError("unknown scope: {}".format(scope))


def collect_scoped_candidates(events, scope, min_confidence):
    cands = []
    global_to_local = {}
    for row in events:
        if is_in_scope(row, scope, min_confidence):
            c = dict(row)
            c["outcome_useful"] = 0
            c["use_event_idx"] = -1
            global_to_local[c["event_idx"]] = len(cands)
            cands.append(c)
    return cands, global_to_local


def assign_useful_labels(events, scope="all", min_confidence=90):
    """Match each USE address to oldest earlier unmatched scoped CAND with same pf_addr."""
    cands, global_to_local = collect_scoped_candidates(events, scope, min_confidence)
    seen_waiting = defaultdict(deque)

    for row in events:
        ev = row.get("event")
        if ev == "CAND" and row["event_idx"] in global_to_local:
            local_i = global_to_local[row["event_idx"]]
            seen_waiting[row["pf_addr"]].append(local_i)
        elif ev == "USE":
            addr = row["addr"]
            if seen_waiting[addr]:
                local_i = seen_waiting[addr].popleft()
                if cands[local_i]["outcome_useful"] == 0:
                    cands[local_i]["outcome_useful"] = 1
                    cands[local_i]["use_event_idx"] = row["event_idx"]

    return cands


def add_online_recent_accuracy(cands):
    """Add prior-only recent accuracy features in event order within the selected scope."""
    cands.sort(key=lambda r: r["event_idx"])

    global_seen = 0
    global_useful = 0
    pc_seen = defaultdict(int)
    pc_useful = defaultdict(int)
    delta_seen = defaultdict(int)
    delta_useful = defaultdict(int)

    for row in cands:
        ip = row["ip"]
        delta = row["delta"]

        row["recent_spp_accuracy"] = global_useful / float(global_seen) if global_seen else 0.5
        row["recent_pc_accuracy"] = pc_useful[ip] / float(pc_seen[ip]) if pc_seen[ip] else 0.5
        row["recent_delta_accuracy"] = delta_useful[delta] / float(delta_seen[delta]) if delta_seen[delta] else 0.5

        y = int(row["outcome_useful"])
        global_seen += 1
        global_useful += y
        pc_seen[ip] += 1
        pc_useful[ip] += y
        delta_seen[delta] += 1
        delta_useful[delta] += y

    return cands


def rows_from_candidates(cands, trace, min_confidence):
    seen_pf = set()
    rows = []
    for c in cands:
        pf = c["pf_addr"]
        duplicate = 1 if pf in seen_pf else 0
        seen_pf.add(pf)

        fill_l2 = 1 if l2_intent(c, min_confidence) else 0
        issued = int(c.get("issued", 0))
        if not c.get("has_issued_col", False):
            issued = fill_l2

        rows.append({
            "trace": trace,
            "cycle": c["event_idx"],
            "ip": c["ip"],
            "addr": c["addr"],
            "pf_addr": c["pf_addr"],
            "delta": c["delta"],
            "spp_confidence": c["confidence"],
            "spp_fill_l2": fill_l2,
            "spp_issued": issued,
            "cache_hit": c["cache_hit"],
            "mshr_occupancy": c["mshr_occupancy"],
            "mshr_size": c["mshr_size"],
            "pq_occupancy": c["pq_occupancy"],
            "pq_size": c["pq_size"],
            "recent_spp_accuracy": "{:.6f}".format(c["recent_spp_accuracy"]),
            "recent_pc_accuracy": "{:.6f}".format(c["recent_pc_accuracy"]),
            "recent_delta_accuracy": "{:.6f}".format(c["recent_delta_accuracy"]),
            "bandwidth_bucket": 0,
            "set_pressure": 0,
            "outcome_useful": int(c["outcome_useful"]),
            "outcome_late": 0,
            "outcome_evicted_unused": 0,
            "outcome_duplicate": duplicate,
        })
    return rows


def build_candidate_table(events, trace, scope, min_confidence):
    all_cands = assign_useful_labels(events, "all", min_confidence)
    scoped_cands = assign_useful_labels(events, scope, min_confidence)
    scoped_cands = add_online_recent_accuracy(scoped_cands)
    rows = rows_from_candidates(scoped_cands, trace, min_confidence)
    return all_cands, scoped_cands, rows


def open_output(path):
    path.parent.mkdir(parents=True, exist_ok=True)
    if str(path).endswith(".gz"):
        return gzip.open(path, "wt", newline="")
    if str(path).endswith(".xz"):
        return lzma.open(path, "wt", newline="")
    return path.open("w", newline="")


def write_rows(path, rows):
    with open_output(path) as f:
        writer = csv.DictWriter(f, fieldnames=OUT_COLUMNS)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def summarize(label, cands):
    total = len(cands)
    useful = sum(int(r["outcome_useful"]) for r in cands)
    acc = useful / float(total) if total else 0.0
    print("[{} candidates]".format(label), total)
    print("[{} useful]".format(label), useful)
    print("[{} candidate accuracy]".format(label), "{:.6f}".format(acc))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--events", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--trace", default="unknown")
    ap.add_argument("--scope", choices=["all", "spp_l2_issue", "spp_actual_issue"], default="spp_actual_issue")
    ap.add_argument("--min-confidence", type=int, default=90)
    args = ap.parse_args()

    events = load_events(args.events)
    has_issued_col = bool(events and events[0].get("has_issued_col", False))
    all_cands, scoped_cands, rows = build_candidate_table(events, args.trace, args.scope, args.min_confidence)
    write_rows(args.out, rows)

    mshr_vals = [int(r["mshr_occupancy"]) for r in rows]
    mshr_avg = sum(mshr_vals) / float(len(rows)) if rows else 0.0
    mshr_max = max(mshr_vals) if mshr_vals else 0

    print("[events]", args.events)
    print("[out]", args.out)
    print("[scope]", args.scope)
    print("[has issued column]", has_issued_col)
    print("[min_confidence]", args.min_confidence)
    summarize("all", all_cands)
    summarize("scoped", scoped_cands)
    print("[mshr avg]", "{:.3f}".format(mshr_avg))
    print("[mshr max]", mshr_max)


if __name__ == "__main__":
    main()
