#!/usr/bin/env python3
"""Summarize demand-centric residual audit event logs.

Input is CSV generated by the Pythia residual logger patch. The event stream has:
  DEMAND rows: one L2C demand LOAD access during ROI
  PF rows:     each L2C prefetch_line request during ROI

Core categories for DEMAND rows:
  covered_on_time = hit == 1 and was_prefetch == 1
  late_prefetch   = hit == 0 and late == 1
  residual_miss   = hit == 0 and late == 0

For residual-booster training, the high-level target is:
  residual_label = residual_miss

No pandas required.
"""

from __future__ import annotations

import argparse
import csv
import gzip
from pathlib import Path
from typing import Dict, List


def open_maybe_gzip(path: Path, mode: str):
    if str(path).endswith(".gz"):
        return gzip.open(path, mode, newline="")
    return path.open(mode, newline="")


def to_int(x, default=0):
    try:
        if x is None or x == "":
            return default
        return int(float(str(x).strip()))
    except Exception:
        return default


def div(a, b):
    return float(a) / float(b) if b else 0.0


def summarize_event_file(trace: str, prefetcher: str, path: Path) -> Dict[str, object]:
    demand = 0
    demand_hit = 0
    demand_miss = 0
    covered_on_time = 0
    late_prefetch = 0
    residual_miss = 0
    ordinary_hit = 0

    pf_requested = 0
    pf_accepted = 0
    pf_duplicate = 0
    pf_dropped = 0

    top_residual_pc: Dict[str, int] = {}
    top_residual_delta: Dict[int, int] = {}
    prev_line_by_pc: Dict[str, int] = {}

    missing = (not path.exists()) or path.stat().st_size == 0
    if not missing:
        with open_maybe_gzip(path, "rt") as f:
            r = csv.DictReader(f)
            for row in r:
                ev = row.get("event", "")
                if ev == "DEMAND":
                    demand += 1
                    hit = to_int(row.get("hit"), 0)
                    was_pf = to_int(row.get("was_prefetch"), 0)
                    late = to_int(row.get("late"), 0)
                    pc = row.get("ip", "0")
                    line = to_int(row.get("line"), 0)

                    if hit:
                        demand_hit += 1
                        if was_pf:
                            covered_on_time += 1
                        else:
                            ordinary_hit += 1
                    else:
                        demand_miss += 1
                        if late:
                            late_prefetch += 1
                        else:
                            residual_miss += 1
                            top_residual_pc[pc] = top_residual_pc.get(pc, 0) + 1
                            if pc in prev_line_by_pc:
                                d = line - prev_line_by_pc[pc]
                                top_residual_delta[d] = top_residual_delta.get(d, 0) + 1
                    prev_line_by_pc[pc] = line

                elif ev == "PF":
                    pf_requested += 1
                    accepted = to_int(row.get("accepted"), 0)
                    duplicate = to_int(row.get("duplicate"), 0)
                    pf_accepted += accepted
                    pf_duplicate += duplicate
                    pf_dropped += int(not accepted)

    top_pc_str = str(sorted(top_residual_pc.items(), key=lambda x: x[1], reverse=True)[:10])
    top_delta_str = str(sorted(top_residual_delta.items(), key=lambda x: x[1], reverse=True)[:10])

    return {
        "trace": trace,
        "prefetcher": prefetcher,
        "event_csv": str(path),
        "log_missing": int(missing),
        "demand": demand,
        "demand_hit": demand_hit,
        "demand_miss": demand_miss,
        "demand_miss_rate": div(demand_miss, demand),
        "covered_on_time": covered_on_time,
        "covered_on_time_rate": div(covered_on_time, demand),
        "coverage_among_misses": div(covered_on_time, demand_miss + covered_on_time),
        "late_prefetch": late_prefetch,
        "late_rate_among_misses": div(late_prefetch, demand_miss),
        "residual_miss": residual_miss,
        "residual_miss_rate": div(residual_miss, demand),
        "residual_share_of_misses": div(residual_miss, demand_miss),
        "ordinary_hit": ordinary_hit,
        "pf_requested_events": pf_requested,
        "pf_accepted_events": pf_accepted,
        "pf_duplicate_events": pf_duplicate,
        "pf_dropped_events": pf_dropped,
        "pf_duplicate_rate": div(pf_duplicate, pf_requested),
        "pf_drop_rate": div(pf_dropped, pf_requested),
        "top_residual_pcs": top_pc_str,
        "top_residual_pc_deltas": top_delta_str,
    }


def write_csv(path: Path, rows: List[Dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = [
        "trace", "prefetcher", "demand", "demand_hit", "demand_miss", "demand_miss_rate",
        "covered_on_time", "covered_on_time_rate", "coverage_among_misses",
        "late_prefetch", "late_rate_among_misses",
        "residual_miss", "residual_miss_rate", "residual_share_of_misses",
        "pf_requested_events", "pf_accepted_events", "pf_duplicate_events", "pf_duplicate_rate", "pf_drop_rate",
        "top_residual_pcs", "top_residual_pc_deltas", "log_missing", "event_csv",
    ]
    with path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        for row in rows:
            w.writerow(row)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--event-root", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--traces", required=True)
    ap.add_argument("--prefetchers", required=True)
    ap.add_argument("--compressed", action="store_true", help="expect .csv.gz instead of .csv")
    args = ap.parse_args()

    suffix = ".events.csv.gz" if args.compressed else ".events.csv"
    rows = []
    for trace in args.traces.split():
        for pf in args.prefetchers.split():
            p = args.event_root / f"{trace}.{pf}{suffix}"
            rows.append(summarize_event_file(trace, pf, p))

    write_csv(args.out, rows)
    print(f"[write] {args.out}")
    for r in rows:
        print(
            f"[residual] {r['trace']} {r['prefetcher']} "
            f"miss_rate={float(r['demand_miss_rate']):.4f} "
            f"covered={float(r['covered_on_time_rate']):.4f} "
            f"late={float(r['late_rate_among_misses']):.4f} "
            f"residual_share={float(r['residual_share_of_misses']):.4f} "
            f"pf_dup={float(r['pf_duplicate_rate']):.4f}"
        )


if __name__ == "__main__":
    main()
