#!/usr/bin/env python3
"""profile_bypass_pcs.py

Reads access_trace.<TRACE>.csv (produced by trace_dumper) and identifies
the top-K PCs whose accesses look like good bypass candidates.

A "good bypass candidate" PC has BOTH:
  (a) high access frequency (it pollutes cache a lot)
  (b) high MISS rate (its line is rarely reused before eviction)

Score = freq * miss_rate
Top-K of these are written to configs/bypass/bypass_pc_list.txt by default,
one PC per line in hex.

Usage:
  python3 scripts/profile_bypass_pcs.py results/access_trace.605.mcf_s-994B.csv \
          --top 10 \
          --out configs/bypass/bypass_pc_list.txt
"""
import argparse, csv, os, sys
from collections import defaultdict

ap = argparse.ArgumentParser()
ap.add_argument('csv', help='access_trace.*.csv from trace_dumper')
ap.add_argument('--top', type=int, default=10, help='how many PCs to bypass (default 10)')
ap.add_argument('--min-freq', type=int, default=1000, help='min access count for a PC to qualify')
ap.add_argument('--out', default='configs/bypass/bypass_pc_list.txt', help='output file path')
args = ap.parse_args()

stats = defaultdict(lambda: {'n': 0, 'hits': 0})

with open(args.csv) as fh:
    rdr = csv.DictReader(fh)
    for row in rdr:
        try:
            pc = int(row['pc_hex'], 16)
            hit = int(row['hit'])
        except (ValueError, KeyError):
            continue
        s = stats[pc]
        s['n']    += 1
        s['hits'] += hit

if not stats:
    print('ERROR: no rows parsed.', file=sys.stderr); sys.exit(1)

# Compute miss rate and score
ranked = []
for pc, s in stats.items():
    if s['n'] < args.min_freq:
        continue
    miss = s['n'] - s['hits']
    miss_rate = miss / s['n']
    score = s['n'] * miss_rate         # weight by frequency
    ranked.append((pc, s['n'], miss_rate, score))

ranked.sort(key=lambda r: -r[3])
top = ranked[:args.top]

print(f'Candidates (top {args.top}):')
print(f'{"PC":>14s}  {"accesses":>10s}  {"miss_rate":>10s}  {"score":>14s}')
for pc, n, mr, sc in top:
    print(f'0x{pc:>12x}  {n:>10d}  {mr:>10.3f}  {sc:>14.0f}')

out_dir = os.path.dirname(args.out)
if out_dir:
    os.makedirs(out_dir, exist_ok=True)

with open(args.out, 'w') as fh:
    fh.write('# Bypass PC list -- one PC per line in hex.\n')
    fh.write(f'# Source: {args.csv}\n')
    fh.write(f'# Generated by profile_bypass_pcs.py with top={args.top}\n')
    for pc, n, mr, sc in top:
        fh.write(f'0x{pc:x}\n')
print(f'\n[saved] {args.out}  ({len(top)} PCs)')
print('Now: BYPASS_PC_LIST=' + args.out + ' bash scripts/run_bypass.sh')
