#!/usr/bin/env python3
"""make_slide8_data.py

Reads results/upper_bound.csv and emits a TikZ \foreach block you can paste
into slide 8 (replacing the placeholder bars).

Usage:  python3 make_slide8_data.py
"""
import csv, os, sys
from collections import defaultdict

R = "results"
ub_file = os.path.join(R, "upper_bound.csv")
if not os.path.exists(ub_file):
    print(f"ERROR: {ub_file} not found. Run run_upper_bound.sh first.", file=sys.stderr)
    sys.exit(1)

# (trace, label, bar centre x on the chart)
ORDER = [
    ("619.lbm_s-4268B",       "streaming",     1.2),
    ("605.mcf_s-994B",        "pointer-chase", 3.8),
    ("620.omnetpp_s-874B",    "indirect",      6.4),
    ("602.gcc_s-734B",        "branch",        9.0),
    ("623.xalancbmk_s-700B",  "mixed",        11.0),
]

# Mapping from chart bar to config tag (must match run_upper_bound.sh)
BAR_CONFIGS = ["lru", "lru_ipstride", "lru_spp", "srrip_spp"]
BAR_COLORS  = ["gray!50", "accent!50", "accent2!50", "accent3!50"]

data = defaultdict(dict)
with open(ub_file) as fh:
    rdr = csv.DictReader(fh)
    for row in rdr:
        try:
            data[row["trace"]][row["config"]] = float(row["IPC"])
        except (ValueError, KeyError):
            pass

all_ipcs = [v for d in data.values() for v in d.values()]
if not all_ipcs:
    print("ERROR: no IPC numbers parsed.", file=sys.stderr); sys.exit(1)
MAX = max(all_ipcs); SCALE = 2.4 / MAX

out = []
out.append("% AUTO-GENERATED by make_slide8_data.py")
out.append("% Paste this in place of the existing \\foreach inside slide 8.")
out.append("")
out.append("\\foreach \\center/\\h/\\hb/\\ho/\\hj in {")
pairs = []
for trace, _label, x in ORDER:
    d = data.get(trace, {})
    bars = [d.get(cfg, 0) * SCALE for cfg in BAR_CONFIGS]
    pairs.append(f"{x:.2f}/{bars[0]:.2f}/{bars[1]:.2f}/{bars[2]:.2f}/{bars[3]:.2f}")
out.append(", ".join(pairs))
out.append("} {")
out.append(f"  \\fill[{BAR_COLORS[0]}] (\\center-0.45,0) rectangle (\\center-0.25,\\h);")
out.append(f"  \\fill[{BAR_COLORS[1]}] (\\center-0.20,0) rectangle (\\center+0.00,\\hb);")
out.append(f"  \\fill[{BAR_COLORS[2]}] (\\center+0.05,0) rectangle (\\center+0.25,\\ho);")
out.append(f"  \\fill[{BAR_COLORS[3]}] (\\center+0.30,0) rectangle (\\center+0.50,\\hj);")
out.append("}")

block = "\n".join(out)
print(block)

with open(os.path.join(R, "slide8_data.tex"), "w") as fh:
    fh.write(block + "\n")
print(f"\n[saved] {os.path.join(R, 'slide8_data.tex')}", file=sys.stderr)
print("[hint] Also update the legend labels in slide 8 to:", file=sys.stderr)
print("       LRU / +IP-stride / +SPP / SRRIP+SPP", file=sys.stderr)